---
# Add system users for default Dovecot authorization
- name: "Create dovecot user {{ item.key }}"
  user:
    name: "{{ item.key }}"
    comment: "Dovecot user"
    password: "{{ item.value.password | password_hash('sha512', item.value.mysecretsalt) }}"
  with_dict: "{{ postfix_users }}"


- include: postfix.yml
- include: dovecot.yml
- include: smtpd.yml
- include: sasl.yml
